
name: Android and iOS Apk/IPA Release
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # to manually run this workflow
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '13' # Specify the desired Xcode version
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter test
        run: flutter test
      - name: Build Android app
        run: flutter build apk --split-per-abi
      - name: Build iOS app
        run: flutter build ios --release --no-codesign
      - name: Push Android artifacts to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.CODE_ACCESS_TOKEN }}
      - name: Push iOS artifacts to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ios/iphoneos/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.CODE_ACCESS_TOKEN }}
